### ISSUE TITLE
20200727_課題概要

### ISSUE THREAD

**Issue by t-manda** [yuyasawa19/LadyBorden#60]
課題：クラス図を完成させる
URL( https://docs.google.com/presentation/d/1j3wQL21SlykMVs-ct3oPGUWNIIika0J7o4yvhLpZWt0/edit#slide=id.g8ea1caff92_0_162 )
変更が在れば、適宜ここに連絡する等、よろしくお願いします。

全員終わったら、また月曜日にpullリクを中井が送る。

**Comment by t-manda** [comment]
リポジトリの部分、終わりました。スペースの関係でスライドを1つ増やしてます。
必要そうな要素があれば、issueに書き込むかスライドに加筆していってください。

**Comment by 208X208X-Shindo** [comment]
リポジトリ問題ないと思います。
UI層の部分、ひとまずできました。確認の方お願いします。

進藤

**Comment by 201x201x** [comment]
サービスの部分、ひとまず書き終えました。
確認をお願いします。

**Comment by tsuno-r** [comment]
アプリケーション層の右半分書き終えました。
確認をお願いします。

**Comment by yuyasawa19** [comment]
連絡し忘れていましたが、アプリケーション層の左半分も書き終えています。
よろしくお願いします。

**Comment by t-manda** [comment]
ざっと見て大丈夫そうだったので、明日にテキストにまとめてコミットします。
お疲れ様でした！
